### ISSUE TITLE
Compilation

### ISSUE THREAD

**Issue by Shahupdates** [Shahupdates/ResumeLinguist#1]
C:\Users\Me\Desktop\ResumeLinguist\venv\Scripts\python.exe C:\Users\Me\Desktop\ResumeLinguist\scraper.py
Data scraped and saved successfully.
C:\Users\Me\Desktop\ResumeLinguist\scraper.py:57: FutureWarning: The default value of regex will change from True to False in a future version.
  data["Location"] = data["Location"].astype(str).str.replace(r"[\(\[].*?[\)\]]", "").str.strip()
Traceback (most recent call last):
  File "C:\Users\Me\Desktop\ResumeLinguist\scraper.py", line 205, in <module>
    extract_features()
  File "C:\Users\Me\Desktop\ResumeLinguist\scraper.py", line 70, in extract_features
    nlp = spacy.load("en_core_web_sm")
  File "C:\Users\Me\Desktop\ResumeLinguist\venv\lib\site-packages\spacy\__init__.py", line 51, in load
    return util.load_model(
  File "C:\Users\Me\Desktop\ResumeLinguist\venv\lib\site-packages\spacy\util.py", line 331, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a Python package or a valid path to a data directory.

Process finished with exit code 1

**Comment by Shahupdates** [comment]
Attempted fix:
```
def extract_features():
    # Load the English language model in spaCy
    nlp = spacy.load("en_core_web_sm", disable=["parser", "ner"])

    # Load the job description data from the CSV file
    data = pd.read_csv("usajobs_data.csv")

    # Extract key skills using spaCy's Named Entity Recognition (NER)
    skills = []
    for description in data["Description"]:
        doc = nlp(description)
        skills.append([ent.text for ent in doc.ents if ent.label_ == "SKILL"])

    # Extract job titles using spaCy's NER
    titles = []
    for description in data["Description"]:
        doc = nlp(description)
        titles.append([ent.text for ent in doc.ents if ent.label_ == "TITLE"])

    # Perform topic modeling using Gensim
    texts = [description.split() for description in data["Description"]]
    dictionary = corpora.Dictionary(texts)
    corpus = [dictionary.doc2bow(text) for text in texts]
    lda_model = models.LdaModel(corpus, num_topics=5, id2word=dictionary)

    # Get the dominant topic for each job description
    topics = [lda_model[corpus[i]][0][0] for i in range(len(corpus))]

    # Add the extracted features to the DataFrame
    data["Skills"] = skills
    data["Titles"] = titles
    data["Topics"] = topics

    # Save the updated data to a new CSV file
    data.to_csv("usajobs_data_with_features.csv", index=False)

    print("Feature extraction completed and data saved successfully.")
```

**Comment by Shahupdates** [comment]
```
C:\Users\Me\Desktop\ResumeLinguist\venv\Scripts\python.exe C:\Users\Me\Desktop\ResumeLinguist\scraper.py
C:\Users\Me\Desktop\ResumeLinguist\scraper.py:57: FutureWarning: The default value of regex will change from True to False in a future version.
  data["Location"] = data["Location"].astype(str).str.replace(r"[\(\[].*?[\)\]]", "").str.strip()
Data scraped and saved successfully.
Traceback (most recent call last):
  File "C:\Users\Me\Desktop\ResumeLinguist\scraper.py", line 205, in <module>
    extract_features()
  File "C:\Users\Me\Desktop\ResumeLinguist\scraper.py", line 91, in extract_features
    lda_model = models.LdaModel(corpus, num_topics=5, id2word=dictionary)
  File "C:\Users\Me\Desktop\ResumeLinguist\venv\lib\site-packages\gensim\models\ldamodel.py", line 447, in __init__
    raise ValueError("cannot compute LDA over an empty collection (no terms)")
ValueError: cannot compute LDA over an empty collection (no terms)
```
New error

**Comment by Shahupdates** [comment]
Page has:
```

TemplateNotFound

jinja2.exceptions.TemplateNotFound: templates/index.html
Traceback (most recent call last)

    File "C:\Users\Me\Desktop\ResumeLinguist\venv\lib\site-packages\flask\app.py", line 2095, in __call__

    return self.wsgi_app(environ, start_response)

    File "C:\Users\Me\Desktop\ResumeLinguist\venv\lib\site-packages\flask\app.py", line 2080, in wsgi_app

    response = self.handle_exception(e)

    File "C:\Users\Me\Desktop\ResumeLinguist\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app

    response = self.full_dispatch_request()

    File "C:\Users\Me\Desktop\ResumeLinguist\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request

    rv = self.handle_user_exception(e)

    File "C:\Users\Me\Desktop\ResumeLinguist\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request

    rv = self.dispatch_request()

    File "C:\Users\Me\Desktop\ResumeLinguist\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request

    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)

    File "C:\Users\Me\Desktop\ResumeLinguist\scraper.py", line 237, in home

    return render_template("templates/index.html")

    File "C:\Users\Me\Desktop\ResumeLinguist\venv\lib\site-packages\flask\templating.py", line 149, in render_template

    ctx.app.jinja_env.get_or_select_template(template_name_or_list),

    File "C:\Users\Me\Desktop\ResumeLinguist\venv\lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template

    return self.get_template(template_name_or_list, parent, globals)

    File "C:\Users\Me\Desktop\ResumeLinguist\venv\lib\site-packages\jinja2\environment.py", line 1010, in get_template

    return self._load_template(name, globals)

    File "C:\Users\Me\Desktop\ResumeLinguist\venv\lib\site-packages\jinja2\environment.py", line 969, in _load_template

    template = self.loader.load(self, name, self.make_globals(globals))

    File "C:\Users\Me\Desktop\ResumeLinguist\venv\lib\site-packages\jinja2\loaders.py", line 126, in load

    source, filename, uptodate = self.get_source(environment, name)

    File "C:\Users\Me\Desktop\ResumeLinguist\venv\lib\site-packages\flask\templating.py", line 59, in get_source

    return self._get_source_fast(environment, template)

    File "C:\Users\Me\Desktop\ResumeLinguist\venv\lib\site-packages\flask\templating.py", line 95, in _get_source_fast

    raise TemplateNotFound(template)

    jinja2.exceptions.TemplateNotFound: templates/index.html

The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.

To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

    dump() shows all variables in the frame
    dump(obj) dumps all that's known about the object

Brought to you by DON'T PANIC, your friendly Werkzeug powered traceback interpreter.

```

**Comment by Shahupdates** [comment]
I seem to be trying to render "templates/index.html". Gonna try changing this to just "index.html". The Flask render_template() function already assumes that your templates will be in a directory named "templates", so I don't need to include that in the path.

Changes:

return render_template("templates/index.html")

to this:

return render_template("index.html")

**Comment by Shahupdates** [comment]
```
@app.route("/", methods=["GET", "POST"])
def home():
    if request.method == "POST":
        job_description = request.form["job_description"]
        if job_description:
            generated_resume = generate_resume(job_description)
            return render_template("index.html", generated_resume=generated_resume)

    return render_template("index.html")
```
